@startuml
skinparam linetype polyline
left to right direction

!function   $safeID($value)
!$parts = %splitstr($value, "-")
!$text = "sid"
!foreach $item in $parts
!$text = $text + "_" + $item
!endfor
!return $text
!endfunction

' рендеринг объектов namespace
frame "{{namespace.name}}" as {{namespace.safeID}} {

    {{#pvcs}}
    together {
        frame "{{name}}\n{{volumeName}}\n{{volumeMode}}\n{{capacity}}\n" as $safeID("pvc_" + "{{name}}") <<claim>>
        'pvc_{{$safeID(name)}} -- dep_vol_{{$safeID(name)}}
    }
    ' Persistent Volume Claims
    {{/pvcs}}

    'сервисы в данном namespace
    {{#services}}
        component "{{name}}" as {{safeID}} <<{{type}}>> {
            rectangle {
                {{#ports}}
                    portin " " as {{safeID}}_in_{{port}}_{{protocol}}
                    portout " " as {{safeID}}_out_{{targetPort}}_{{protocol}}
                    card "{{name}}:{{protocol}}" as {{safeID}}_{{port}}_{{targetPort}}_{{protocol}}
                    {{safeID}}_in_{{port}}_{{protocol}} -0)- {{safeID}}_{{port}}_{{targetPort}}_{{protocol}} : {{port}}
                    {{safeID}}_{{port}}_{{targetPort}}_{{protocol}} -0)- {{safeID}}_out_{{targetPort}}_{{protocol}} : {{targetPort}}
                {{/ports}}
            }
        }
        ' отображение NodePort на границе NS
        {{#ports}}
            {{#nodePort}}
                portin " " as {{safeID}}_node_in_{{port}}
                {{safeID}}_node_in_{{port}} -0)- {{safeID}}_in_{{port}}_{{protocol}} : {{nodePort}}
            {{/nodePort}}
        {{/ports}}
    {{/services}}
    together {
        {{#deployments}}
        component "== {{name}}\nреплик: {{replicas}}\n" as {{safeID}} <<deployment>> {
            {{#volumes}}
                card "{{name}}\n{{#claim}}claim: {{name}}{{/claim}}" as $safeID({{safeID}} + "_dep_vlm_" + "{{name}}") <<volume>>
                'card $safeID("ABC" + {{safeID}} + "_dep_vlm_" + "{{name}}") <<volume>>
            {{/volumes}}
            {{#pvcLinks}}
                $safeID({{safeID}} + "_dep_vlm_" + "{{name}}") -- $safeID("pvc_" + "{{claim.name}}")
            {{/pvcLinks}}
            {{#containers}}
                component "== {{name}}\n====\n{{{image}}}\n\n" <<container>> {
                    {{#ports}}
                        portin " " as {{safeID}}_in_{{port}}_{{protocol}}
                    {{/ports}}
                    {{#mounts}}
                        'точка монтирования пути на volume
                        artifact "volume: {{name}}\n{{{path}}}" as $safeID({{safeID}} + "_dep_mnt_" + "{{name}}") <<mount>>
                        $safeID({{safeID}} + "_dep_mnt_" + "{{name}}") -- $safeID({{safeID}} + "_dep_vlm_" + "{{name}}")
                        '$safeID({{safeID}} + "_dep_mnt_" + {{name}}) --

                        '{{safeID}}_dep_mnt_{{$safeID(name)}} -- dep_vol_{{$safeID(name)}}
                        'card $safeID("XXX_" + {{name}})
                    {{/mounts}}
                }
            {{/containers}}
        }
        {{/deployments}}
    }

    {{#links}}
        {{#deployments}}
            {{service.safeID}} -[hidden]- {{safeID}}
            {{#service.ports}}
                {{service.safeID}}_out_{{port}}_{{protocol}} -- {{safeID}}_in_{{targetPort}}_{{protocol}} : {{targetPort}}
            {{/service.ports}}
        {{/deployments}}
    {{/links}}
}

{{#pvs}}
    ' persistent volume
    folder "{{name}}\n{{capacity}}\n{{volumeMode}}" <<persistent volume>> as {{safeID}}
    ' it's link to PVC
    $safeID("pvc_" + "{{claimRef.name}}") -- {{safeID}}

{{/pvs}}
'ABC
