entities:
    seaf.ta.services.k8s:
        menu: >
            (
                $kubernetes_menu_generator := function($prefix, $domain){(
                    [
                        {
                            'location': $prefix & '/Kubernetes/Кластера',
                            'link': 'entities/seaf.ta.services.k8s/k8s_list?domain=' & $domain
                        }
                    ]
                )};
                sber.kadzo ? (
                    sber.kadzo.enterprise_mode ?
                    sber.domains.$spread().( 
                        $domain := $keys(); 
                        $title := $lookup($$.companies, $domain) ? $lookup($$.companies, $domain).title : $.*.title;
                        $prefix := "ДЗО/" & $title & "/Реверс";
                        $kubernetes_menu_generator($prefix, $domain);
                    ) : (
                          $not($exists(sber.kadzo.enterprise_mode)) and (sber.kadzo.menu.architecture.enabled = true or $not($exists(sber.kadzo.menu.architecture.enabled))) ? (
                              $menu_root := ($exists(sber.kadzo.menu.architecture.roots) and $count(sber.kadzo.menu.architecture.roots) > 0 and $not(sber.kadzo.menu.architecture.roots = null))  ? sber.kadzo.menu.architecture.roots :
                                              $exists(sber.kadzo.menu_root) ? sber.kadzo.menu_root : "Документы/Сбер/КА ДЗО/2023";
                          $domain := sber.domain;
                          $prefix := $menu_root & "/Реверс";
                          $kubernetes_menu_generator($prefix, $domain);
                        )
                    ) 
                ) : (
                    $config := "seaf.ta.reverse.general".config;
                    $prefix := $config.arch_menu;
                    $domain := "";
                    $kubernetes_menu_generator($prefix, $domain);
                );
            )