entities:
    seaf.ta.services.k8s:
        menu: >
            (
                $config := entities."seaf.ta.reverse.general".config;
                $kube_config := entities."seaf.ta.reverse.k8s".config;
            
                [
                    {
                        'location': $config.arch_menu & '/Kubernetes/Кластера',
                        'link': 'entities/' & $kube_config.cluster.entity & '/' & $kube_config.cluster.view  
                    }
                ]
            )