entities:
    seaf.ta.reverse.k8s.node:
        presentations:
            table_view:
                type: table
                headers:
                - value: name
                  text: Название
                  width: 200
                  sortable: true
                  link: link
                - value: cluster
                  text: Кластер
                  width: 200
                  sortable: true
                  link: link
                source: > 
                    (
                        $nodes := $."seaf.ta.reverse.k8s.node"; 
                        [$nodes.$spread().(
                            {
                                "name" : $.*.name,
                                "cluster": $.*.cluster
                            }
                        )]
                    )
                    
