entities:
    seaf.ta.components.k8s.node:
        presentations:
            list:
                type: table
                headers:
                - value: name
                  text: Название
                  width: 200
                  sortable: true
                  link: link
                - value: cluster
                  text: Кластер
                  width: 200
                  sortable: true
                  link: link
                source: > 
                    (
                        $nodes := $."seaf.ta.reverse.k8s.node"; 
                        [$nodes.$spread().(
                            {
                                "name" : $.*.name,
                                "cluster": $.*.cluster
                            }
                        )]
                    )
                    
            get:
                type: markdown
                template: templates/node.md
                source: >
                    (
                        $node_id := "seaf.ta.components.k8s.node." & $params.id;
                        $node    := $."seaf.ta.components.k8s.node".$spread()[$keys()[0] = $node_id];
                        {                        
                            "id"            : $params.id,
                            "node_id"       : $node_id,
                            "name"          : $node.*.name,
                            "arch"          : $node.*.architecture,
                            "cpu"           : $node.*.cpu,
                            "addresses"     : $node.*.addresses
                        }
                    )
