entities:
    seaf.ta.components.k8s.node:
        title: Kubernetes cluster node
        objects:
            node:
                route: "/"
                title: Kubernetes cluster node
        schema:
            type: object
            patternProperties:
                "^[a-zA-Z][a-zA-Z0-9_-]*(\\.[a-zA-Z][a-zA-Z0-9_-]*)*$":
                    type: object
                    properties:
                        id:
                            title: ID ноды
                            type: string
                        clusterID:
                            title: ID кластера ноды
                            type: string
                        name:
                            title: имя ноды
                            type: string
                        version:
                            title: версия k8s
                            type: string
                    required:
                        - id
                        - clusterID
                        - name