gantt
    dateFormat  YY-MM-DD
    axisFormat w%W, %d.%m
    title       Дорожная карта развития IaaS extension SEAF 2024
    section IaaS Реверс
        Реверс Managed Kubernetes                                           :       24-03-20, 30d
        Реверс Cloud.ru Облако VMware                                          :       24-02-09, 60d
        Реверс VmWare Private Cloud (vCenter, PowerCLI)                     :       24-02-20, 60d
        Взаимодействие со скриптом по API                                   :       24-04-02, 45d
        Адаптация кейса реверса слоя приложений (Gitlab, Ansible, LinkerD)  :       24-01-09, 200d

